#pragma once

#include <od/core/api.h>

// Build settings
#if !defined(OD_BUILD_DLL_ENGINE_PLATFORM)
#define OD_BUILD_DLL_ENGINE_PLATFORM 0
#endif

// API decorators
#if OD_BUILD_DLL_ENGINE_PLATFORM
#define OD_API_PLATFORM_LINKAGE_SHARED OD_API_LINKAGE_EXPORT
#else
#define OD_API_PLATFORM_LINKAGE_SHARED OD_API_LINKAGE_IMPORT
#endif

#define OD_API_PLATFORM_C OD_API_LINKAGE_NAMES_C OD_API_PLATFORM_LINKAGE_SHARED 
#define OD_API_PLATFORM_CPP OD_API_PLATFORM_LINKAGE_SHARED 
