#pragma once

#include <od/core/api.h>

// Build settings
#if !defined(OD_BUILD_MODULE_ENGINE_DEBUG_GUI)
#define OD_BUILD_MODULE_ENGINE_DEBUG_GUI 0
#endif

// API decorators
#if OD_BUILD_DLL && OD_BUILD_MODULE_ENGINE_DEBUG_GUI
#define OD_API_ENGINE_DEBUG_GUI_LINKAGE_SHARED OD_API_LINKAGE_EXPORT
#else
#define OD_API_ENGINE_DEBUG_GUI_LINKAGE_SHARED OD_API_LINKAGE_IMPORT
#endif

#define OD_ENGINE_DEBUG_GUI_API_C OD_API_LINKAGE_NAMES_C OD_API_ENGINE_DEBUG_GUI_LINKAGE_SHARED 
#define OD_ENGINE_DEBUG_GUI_API_CPP OD_API_ENGINE_DEBUG_GUI_LINKAGE_SHARED 
